version: 2.1
orbs:
  node: circleci/node@5
  evals: circleci/evals@2.0
jobs:
  test-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          name: Run tests
          command: npm test --passWithNoTests
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: "#e.g. ./deploy.sh"
      - run:
          name: found github actions config
          command: ":"
  evals-test-assertions-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - evals/test:
          assertions: assertions.json
          metrics: eval_results.json
          results: test_results.xml
workflows:
  build-and-test:
    jobs:
      - test-node:
          context:
            - Gemini-Rich
  test-eval-workflow:
    jobs:
      - evals-test-assertions-job
